language: python
python:
- '3.6'
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- black --check $TRAVIS_BUILD_DIR
- flake8
- coverage run --source='.' manage.py test mysite
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: jRC9xg29O1KZVlggF4oAhi8o1al/lf4tDBw9EGt9BkIPwLb8kEmlCZAtL/PAMbQnO4MW/ZM0Ni2WWVdlKuUgR6pvGdcUmGUjLhX406sKTsgYXpMQH+YGvpxFUXZCH6jQ7498xAiqvavbYo9eqEX3wP5yG5YELqct1VQOQJWxKEdaHWoQoD05gBEElPCL3RQEVoxjiEhaxD8PmgHa2uuLCbPSQUopsjsDJLnXwI5VA0fvi5tnF8fhFB3fc4u7I2a6aW96AMGq8LtJMNfddX6QJ/yCulLAIL9r7ieVkYsbFc82424BwOHlloqPjYh64b9ROLwqnSqiLTjrKawp6Sy9mdNqmmqzRv4IqiWjIW1unW1OQhTQGV3mdMNkEaXev6jCdqRZKq6sW+fQrR6sdDnH0wYkLQWK9Of20iQpaQAyCpLf16XSyUZrNmimSVQIwJXhkouSyFtYtJiIX/qTvuOEdjUv1kRlh2AR92JbWGg/nQPDBXkg7IUnGKPAH3Doprm3fsjfuIH2nUffDu3wsExvtdIZ2r0ZVmnRSNR23/zLnuYXW8TSGmVr3t8eKyeC9CzSdHsm35xKjUFprVvM3NbixpTydo0Lk/4JhmRgWJadjOCvNvOr2dkAg5UBOCr8/a0XS1ETl7H72v9Gbrv35P4s9jqt9Qonfb2ExHBT0beDx/c=
